<a href="https://colab.research.google.com/github/Racoo203/LearnPyTorch/blob/main/1Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensores e inicio.

Importancion de la librearia
- Pytorch -> Import torch

Con esta forma podemos descargar toda la libreria de Pytorch
Esta libreria contiene todo lo necesario para poder manejar redes neuronales dentro de Python. Existen analogas como TensorFlow, pero por motivos tecnicos, manejaremos Pytorch para mayor comodidad.

In [ ]:
import torch

c:\Users\Felip\Miniconda3\envs\MLearn\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Como introducción vamos a presentar el concepto de **Tensor**. Normalmente conocemos cosas como los __Vectores__, que son objetos que permiten guardar información en filas. Pero mas precisamente, todos los tipos de datos que miramos, ya sea, numero, vector, matriz, son tensores, pero de dimensiones pequeñas. 

En Python normalmente a un vector le llamamos *Lista* la cual tiene la propiedad de guardar N valores dentro de un objeto, he aqui un ejemplo:

In [ ]:
# Crear una lista con 5 elementos
lista = [1, 2, 3, 4, 5]
print(lista)

[1, 2, 3, 4, 5]


Esta lista contiene **5** valores dentro, pero a la vez, nosotros podemos verlo como un vector de 5 dimensiones. La notación para denotar las dimensiones de los vectores usamos $\R^{n}$, donde $n$ es el numero de dimensiones con las que definimos al vector, en este caso el vector _lista_ que tenemos, tiene una dimension de $R^{5}$, y de esa forma tenemos los vectores.

Ocurre que, pytorch no maneja las listas de python como un vector, por lo que tenemos que pasarlo de Lista_python -> Vector_pytorch, para eso existe una función que convierte las listas a vectores de pytorch. Esta funcion es

_Lista_ -> _Tensor_ [**torch.Tensor(Lista)**]

Podemos definir la función y probarla con la lista que ya habiamos definido.

In [ ]:
vector = torch.tensor(lista)
print(vector)

tensor([1, 2, 3, 4, 5])


Como podemos ver, tenemos que convertimos la lista de 5 elementos a un vector de 5 dimensiones.

Realmente un Vector es un tensor, los tensores son objetos que guardan valores en objetos de multidimensiones. Como ya habia dicho, los numeros normales son tambien vectores, pero en este caso es un Tensor de tamaño 0. Un vector es un Tensor de tamaño 1xn, una matriz es un tensor de tamaño 2, con nxm dimensiones, cuando el tamaño es mayor a 3, se le empieza a llamar "Tensor" y tienen la forma de a x b x c ... x n  dimensiones. 

Para poder checar el tamaño de un Tensor, el objeto tensor tiene la variable shape, la cual se llama de la siguiente manera

*Retorno del tamaño*

Si tenemos un Tensor llamado objeto, podemos saber su tamaño si usamos la opción:

_objeto.shape_

He aqui un ejemplo:

In [ ]:
# Definir un tensor objeto en base a una lista de listas
lista = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
tensor = torch.tensor(lista)
# Retornar el tamaño del tensor
print(tensor.shape)

torch.Size([3, 3])


### Indexación de Tensores

Los tensores son objetos que guardan valores en una lista, por lo que podemos acceder a ellos de la misma forma que accedemos a una lista. Para acceder a un elemento de un tensor, usamos la siguiente notación:

In [ ]:
# Indexar un tensor
print(tensor[0]) # Primer elemento Como tiene varias dimensiones, retorna un tensor
print(tensor[0][0]) # Primer elemento del primer elemento

tensor([1, 2, 3])
tensor(1)


Una lista de listas es una representación de una matriz, el cual es un Tensor de tamaño nxm , en este caso tiene un tamaño de 2, con las dimensiones 3 x 3, de esta forma podemos ir expandiendo la dimension a un tamaño de 3, pudiendo pasar de una matriz a un cubo, siendo de M x N x K y asi infinitamente.

Pytorch tiene funciones que permiten generar Tensores de tamaño definido, pero no con valores valores vacios dentro. Existen varias funciones que podemos usar para poder tener los Tensores, las siguientes son ejemplos de funciones:

*Tensor de puros valores 0*

In [ ]:
# Generar un Tensor de tamaño [2,3 ,4] de puros ceros
Zero_Tensor = torch.zeros([2, 2, 3])
print(Zero_Tensor)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


*Tensor de puros valores 1*

In [ ]:
# Generar un Tensor de tamaño [2,3 ,4] de puros unos
One_Tensor = torch.ones([2, 2, 3])
print(One_Tensor)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


*Tensor de valores aleatorios entre 0 y 1*

In [ ]:
# Generar un Tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 2, 3])
print(Random_Tensor)

tensor([[[0.7121, 0.1243, 0.7605],
         [0.1065, 0.0952, 0.9642]],

        [[0.6545, 0.5998, 0.1234],
         [0.2058, 0.8193, 0.6076]]])


## Operación entre Tensores

Al igual que la suma entre numeros o vectores, los tensores tienen de igual menera sus operadores, los cuales, los mas basicos son los siguientes

*Operadores*
- Suma / Resta
- Multiplicación por Hadamard o Wise-to-Wise
- Producto Punto
- División

### Suma
Al igual que con una matriz, si hacemos una suma entre Tensores existen varios casos en los que cada uno tiene un resultado distinto dependiendo de los tamaños de los Tensores.

*Suma con un numero*

Si tenemos un Tensor llamado A, al restarle un valor entero, como por ejemplo, 1, tenemos que este valor se resta a cada uno de los valores del Tensor A, el siguiente es un ejemplo.

In [ ]:
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios y restarle un valor x
Random_Tensor = torch.rand([2, 2, 3])
x = 0.5
print(Random_Tensor)
print(Random_Tensor - x)

tensor([[[0.9760, 0.6638, 0.0548],
         [0.4083, 0.7022, 0.1139]],

        [[0.4340, 0.2360, 0.9260],
         [0.2792, 0.5184, 0.1163]]])
tensor([[[ 0.4760,  0.1638, -0.4452],
         [-0.0917,  0.2022, -0.3861]],

        [[-0.0660, -0.2640,  0.4260],
         [-0.2208,  0.0184, -0.3837]]])


*Suma con un Tensor menor*

Si tenemos un Tensor llamado A, y otro Tensor B, ocurre que si el vector B es de un tamaño menor al de A, pero coinciden el resto de las dimensiones, este Tensor se restara a todos los Tensores del Tensor mas grande. Esto es complicado de ver a simple vista, pero el siguiente ejemplo puede entenderse mejor:

In [ ]:
# Hacer una suma de Tensores donde uno de ellos es de menor tamaño
x = torch.zeros([2, 2, 3])
y = torch.randint(1, 10, [2, 3])
print(x + y)
# En este caso se suma el tensor Y a cada uno de los elementos del tensor X
# He aqui otro ejemplo
x = torch.zeros([2, 2, 3])
y = torch.randint(1, 10, [2, 1, 3])
print(x + y)
# En este caso se suma el tensor Y a cada uno de los elementos del tensor X pero 
# en este caso el tensor Y es de menor tamaño que el tensor X y se cambia el eje 1

tensor([[[3., 1., 5.],
         [1., 4., 5.]],

        [[3., 1., 5.],
         [1., 4., 5.]]])
tensor([[[3., 1., 7.],
         [3., 1., 7.]],

        [[2., 7., 1.],
         [2., 7., 1.]]])


Todo esto ocurre igualmente con la resta de los vectores, por lo que no queda mucho el explicaro.


*Multiplicación con un numero*

Si tenemos un Tensor llamado A, podemos multiplicarle un numero entero, el cual se multiplicara a cada uno de los valores del tensor.

In [ ]:
# Multiplicar un tensor por un escalar
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.ones([2, 2, 3])
x = 0.5
print(Random_Tensor)
print(Random_Tensor * x)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]],

        [[0.5000, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.5000]]])



*Multiplicación con un Tensor*

Si tenemos un Tensor llamado A y un Tensor llamado B, al igual que con la suma, podemos hacer tanto la multiplicación de Tensor, haciendo que cada elemento del Tensor se multiplique por el elemento de Tensor:

In [ ]:
# Multiplicar un tensor por otro tensor
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 2, 3])
x = torch.ones([2, 2, 3])
print(Random_Tensor)
print(x)
print(Random_Tensor * x)

tensor([[[0.4942, 0.7548, 0.4827],
         [0.7563, 0.0076, 0.3158]],

        [[0.9523, 0.5114, 0.4759],
         [0.4838, 0.7487, 0.5460]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0.4942, 0.7548, 0.4827],
         [0.7563, 0.0076, 0.3158]],

        [[0.9523, 0.5114, 0.4759],
         [0.4838, 0.7487, 0.5460]]])



## Producto Punto entre Tensores

La herramienta del producto punto entre los tensores realmente no se utiliza demasiado para Tensores de tamaño mayor a 3, por lo que no utilizaremos realmente la aplicación para un tamaño mayor a 2.

El producto punto entre 2 Tensores de tamaño 2 es algo complicado, ya que no tiene una definición sencilla, pero para poder entender mejor como funciona podemos hacerlo ver entre 2 vectores. 

El producto punto entre 2 vectores es algo mas sencillo de ver, ya que si tenemos un vector $A = [1,2,3]$ y un vector $B = [2,3,-1]$, el producto punto esta definido como $A\cdot B=A_1*B_1+A_2*B_2+A_3*B_3+...+A_n*B_n$

En este caso, si tenemos los vectores A y B, tenemos $A\cdot B=1*2+2*3+3*-1=5$

La forma en la que hacemos los productos punto entre 2 vectores en pytorch es variada, existen muchos metodos, el primero es escoger el primer vector y llamar a su función .dot

_A = Tensor ([1,2,3])_

_B = Tensor ([2,3,-1])_
_A.dot(B)_

Esta función retorna el valor de A con el producto de B y no lo modifica, he aqui el ejemplo:

In [ ]:
# Producto punto entre 2 vectores
A = torch.tensor([1, 2, 3]) # Vector A
B = torch.tensor([2, 3, -1]) # Vector B
print(A.dot(B)) # Producto punto entre A y B
print(A) # Vector A original y sin modificar

tensor(5)
tensor([1, 2, 3])


El segundo metodo es llamando a la libreria Pytorch y sacar la funcion matmul(A,B), que devuelve exactamente el producto punto.

In [ ]:
# Hacer producto punto entre 2 vectores pero con la funcion matmul
A = torch.tensor([1, 2, 3]) # Vector A
B = torch.tensor([2, 3, -1]) # Vector B
print(torch.matmul(A, B)) # Producto punto entre A y B

tensor(5)


El tercer metodo es usando el operador @, que al igual que + es para suma, - es para resta, * es para multiplicación, @ es para el producto punto.

In [ ]:
# Utilizar @ para hacer producto punto entre 2 vectores
A = torch.tensor([1, 2, 3]) # Vector A
B = torch.tensor([2, 3, -1]) # Vector B
print(A @ B) # Producto punto entre A y B

tensor(5)


Una vez definido el producto punto de 2 vectores, podemos expandir el resultado a matrices. Como vimos entre 2 vectores, es volver un vector del mismo tamaño en un valor escalar. En este caso si tenemos una matriz, hacemos el mismo proceso para vectores dentro de la matriz. Si tenemos las matrices:

In [ ]:
# Generar una matriz para testear el producto punto
A = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Matriz A de 2x3
# Crear una matriz de 3x2
B = torch.tensor([[1, 2], [3, 4], [5, 6]]) # Matriz B de 3x2
print(A.shape)
print(B.shape)
print(A)
print(B)

torch.Size([2, 3])
torch.Size([3, 2])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


Podemos agarrar la matriz y dividirla en vectores, en este caso podemos partir la matriz A en 2 vectores $A_1 = [1,2,3]$ , y el vector $A_2 = [4,5,6]$ los cuales son vectores horizontales, o tensores de tamaño 1xn, de la misma manera con la matriz B, pero ahora son vectores verticales nx1 $B_1 = [1,2,3]$, y el vector $B_2 = [4,5,6]$, por lo que tenemos el producto punto entre cada vector horizontal de A por el resto del vector vertical de B, por lo que tenemos 4 operaciones: [$A_1\cdot B_1, A_1\cdot B_2, A_2\cdot B_1, A_2\cdot B_2$]

Cada producto punto entre los vectores es un valor unico y final, no se suman y forman otra matriz, por lo que tenemos una matriz final con el resultado de los productos punto. Y esto genera un objeto nuevo, pero el producto punto de matrices posee algunas propiedades.

**Propiedades del producto punto**
Si tenemos 2 matrices A y B de tamaño 3x4 y 4x5 respectivamente. Al hacer un producto entre estas Matrices, el resultado final sera de tamaño 3x5. Por lo que tenemos la regla general de.

Si A tiene dimensión (MxN) y B tiene dimensión (NxK)

A@B = C y C tiene como dimensión (MxK)

Ejemplo:

In [ ]:
# Hacer el producto punto entre las 2 matrices y mostrar el cambio de tamaño
A = torch.rand([3, 4]) # Matriz A de 2x3
B = torch.rand([4, 5]) # Matriz B de 3x2
print(A.shape)
print(B.shape)
# Hacer el producto punto entre las 2 matrices e imprimir el resultado
print(torch.matmul(A, B).shape)
print(torch.matmul(A, B))

torch.Size([3, 4])
torch.Size([4, 5])
torch.Size([3, 5])
tensor([[0.8149, 0.6820, 0.4488, 0.9432, 0.5451],
        [0.9957, 1.2316, 1.3285, 1.5159, 0.9733],
        [0.8456, 1.3437, 1.6448, 1.7620, 1.0040]])


## Funciones para Tensores

Una vez ya vistas las operaciones de Tensores, podemos ver funciones que nos otorga Pytorch para manejar Tensores.

### Squeeze

In [ ]:
# Presentar las funciones de Pytorch para manejo de tensores
# Squeeze
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 1, 1, 3, 1, 3])
print(Random_Tensor.shape)
# La funcion squeeze elimina los elementos de tamaño 1 y reduce las dimensiones extra
print(Random_Tensor.squeeze().shape)
# A la vez puedes escoger que dimensiones quieres eliminar
print(Random_Tensor.squeeze(1).shape) # Elimina la dimension 1

torch.Size([2, 1, 1, 3, 1, 3])
torch.Size([2, 3, 3])
torch.Size([2, 1, 3, 1, 3])


### Unsqueeze

In [ ]:
# Unsqueeze
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 3, 4])
print(Random_Tensor.shape)
# La funcion unsqueeze agrega una dimension de tamaño 1
print(Random_Tensor.unsqueeze(0).shape)
# A la vez puedes escoger que dimensiones quieres agregar
print(Random_Tensor.unsqueeze(1).shape) # Agrega la dimension 1

torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([2, 1, 3, 4])


### Transpose

In [ ]:
# Transpose
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 3, 4])
print(Random_Tensor.shape)
# La funcion transpose cambia las dimensiones
print(Random_Tensor.transpose(0, 1).shape) # Cambia la dimension 0 por la 1
print(Random_Tensor.transpose(1, 2).shape) # Cambia la dimension 1 por la 2
print(Random_Tensor.transpose(0, 2).shape) # Cambia la dimension 0 por la 2

torch.Size([2, 3, 4])
torch.Size([3, 2, 4])
torch.Size([2, 4, 3])
torch.Size([4, 3, 2])


### Permute

In [ ]:
# Permute
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 3, 4])
print(Random_Tensor.shape)
# La funcion permute cambia las dimensiones
print(Random_Tensor.permute(0, 1, 2).shape) # Cambia la dimension 0 por la 1
print(Random_Tensor.permute(1, 2, 0).shape) # Cambia la dimension 1 por la 2
print(Random_Tensor.permute(2, 0, 1).shape) # Cambia la dimension 0 por la 2

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
torch.Size([3, 4, 2])
torch.Size([4, 2, 3])


### Transpose

In [ ]:
# View
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 3, 4])
print(Random_Tensor.shape, "Original")
# La funcion view cambia las dimensiones del tensor pero no cambia el tamaño, conserva los datos
print(Random_Tensor.view(-1, 12).shape) # Cambia las dimensiones a 2x12
# el termino -1 indica que el tamaño de esa dimension se calcula automaticamente
print(Random_Tensor.view(-1, 6).shape) # Cambia las dimensiones a 4x6
# Tambien podemos hacer que un tensor se aplane
print(Random_Tensor.view(-1).shape,"Aplanado") # Aplana el tensor
# Tambien podemos hacer que un tensor plano se vuelva a su forma original
plane_tensor = torch.rand([24])
print(plane_tensor.shape, "Original")
print(plane_tensor.view(2, 3, 4).shape, "Vuelto a su forma original")


torch.Size([2, 3, 4]) Original
torch.Size([2, 12])
torch.Size([4, 6])
torch.Size([24]) Aplanado
torch.Size([24]) Original
torch.Size([2, 3, 4]) Vuelto a su forma original


In [ ]:
# Otra funcion para cambiar las dimensiones de un tensor es la funcion reshape
# Generar un tensor de tamaño [2,3 ,4] de valores aleatorios
Random_Tensor = torch.rand([2, 3, 4])
print(Random_Tensor.shape, "Original")
# La funcion reshape cambia las dimensiones del tensor pero no cambia el tamaño, conserva los datos
print(Random_Tensor.reshape(-1, 12).shape) # Cambia las dimensiones a 2x12
# De esta forma funciona igual que la funcion view

torch.Size([2, 3, 4]) Original
torch.Size([2, 12])
