<a href="https://colab.research.google.com/github/Racoo203/LearnPyTorch/blob/main/2Calculo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Calculo de Tensores

Al igual que con los vectores y las matrices, podemos aplicar la teoria del calculo en los tensores. La ventaja de todo esto es que los calculos que se hacen son bastante similares al calculo clasico.

### Calcular la derivada

La ventaja de utilizar Pytorch con respecto al resto de librerias es que, cada vez que utilizas o hacemos operacion de Tensores, dentro de estos se guarda en la memoria cada operación que hacemos, por lo que al resultado final podemos aplicarle una función llamada .backward() que es la derivada de lo que se calculo.

### Un ejemplo de función Backward

Si tenemos el tensor X, podemos hacer que lo elevemos al cuadrado y le sumemos X, teniendo 

$Y = X^2 + X$

In [ ]:
import torch

c:\Users\Felip\Miniconda3\envs\MLearn\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# Probar la función Backward con un ejemplo
# Tensor X y hacer la formula
# Y = X^2 + X
# Su derivada es 2X + 1
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32, requires_grad=True)
Y = X**2 + X
Y.backward(torch.tensor([1, 1, 1, 1], dtype=torch.float32))
print(X.grad)
# En este caso el resultado es el mismo que la derivada
# de la función, teniendo Y' = 2X + 1
# Y' = 2*1 + 1 = 3
# Y' = 2*2 + 1 = 5
# Y' = 2*3 + 1 = 7
# Y' = 2*4 + 1 = 9


tensor([6., 5., 7., 9.])


De esta forma, tenemos una forma sencilla de poder calcular las derivadas de las operaciones que hagamos con los vectores con respecto a un valor.

In [ ]:
# Probar la función Backward con un ejemplo
# Tensor X y hacer la formula
# Y = X^2 + X
# Su derivada es 2X + 1
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32, requires_grad=True)
Y = X**2 + X
Y.backward(torch.tensor([2, 3, 4, 5], dtype=torch.float32))
print(X.grad)

tensor([ 6., 15., 28., 45.])


Podemos a la vez definir funciones que nos devuelvan valores y aun asi la derivada se va a conservar, esto es porque las operaciones se guardan en la memoria incluso como función.

In [ ]:
# Definir una función para demostrar el uso de la función Backward con funcinoes de python

def function(x):
    return x**3 + 2*x**2 + 3*x + 4 # Derivada de la función es 3x^2 + 4x + 3

X = torch.tensor([1, 2, 3, 4], dtype=torch.float32, requires_grad=True)
Y = function(X)
Y.backward(torch.tensor([1, 1, 1, 1], dtype=torch.float32))
print(X.grad)
    

tensor([10., 23., 42., 67.])
